language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
before_script:
  - python manage.py collectstatic --noinput
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
