language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
addons:
  chrome: stable
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - echo $PATH

script:
  - python manage.py test
